### ISSUE TITLE
Failed to install ronn-ng because of ruby 3

### ISSUE THREAD

**Issue by spacewander** [apjanke/ronn-ng#100]
When installing ronn-ng, I got an error like this:
```
mustache-1.0.0 requires Ruby version ~> 2.0. The current ruby version is 3.2.2.
```

We should upgrade the version of mustache in https://github.com/apjanke/ronn-ng/blob/0f42377f9c9102946f8d3980b5bec40c3fafde24/ronn-ng.gemspec#L63, as the old mustache requires Ruby 2, see https://github.com/mustache/mustache/commit/fa046db4f6c253e104d71817180c12678aa055a5.

**Comment by apjanke** [comment]
Yep yep. This sounds like an easy fix. I'll try to get to it tomorrow.
