### ISSUE TITLE
Add Homebrew formula

### ISSUE THREAD

**Issue by apjanke** [apjanke/ronn-ng#20]
Since `ronn-ng` is a binary that comes with shell completion files and the like, a straight `gem` install isn't adequate to get it all set up. Better to have it distributed by package managers.

Create a Homebrew formula in a custom tap to get it started.

Need to figure out what to do for Linux, too. I don't want to maintain packages for the various Linux distros.

**Comment by hosiet** [comment]
You may leave packaging issue in Linux distributions to distribution developers. @apjanke Please consider opening a separate issue and we may discuss in detail there.

**Comment by apjanke** [comment]
Cool. Here's an issue for discussing Linux packaging: #21.

**Comment by apjanke** [comment]
Homebrew formula created.

Custom tap here: https://github.com/apjanke/homebrew-ronn-ng.
Added installation instructions in https://github.com/apjanke/ronn-ng/commit/5cb61ca11a1b4e4e7b1c8786419ff6706d748d7d.
