### ISSUE TITLE
Linux packaging

### ISSUE THREAD

**Issue by apjanke** [apjanke/ronn-ng#21]
For distribution on Linux, I'd like to get Ronn-NG supported by major Linux distributions' package managers. Figure out how to do that.

Questions to consider:
* How to announce the project to Linux packagers?
* How mature should the project be before doing so? How likely are package managers to accept it?
* Would a Makefile with a `make install` that works on Linux be a good short-term substitute?

**Comment by hosiet** [comment]
For Debian, the legacy ronn is being tracked at: https://tracker.debian.org/pkg/ruby-ronn . This package will migrate down onto all other deb-based distributions.

It might be a good idea to ask Debian's packagers to switch upstream and package new releases if ronn-ng is mostly compatible with the old ronn for users.

As for build system (Makefile, etc), personally I know nothing about Ruby ecosystem but I guess a standard and universal buildsystem would certainly be better than a custom Makefile.

**Comment by apjanke** [comment]
Thanks for the pointers.

> It might be a good idea to ask Debian's packagers to switch upstream and package new releases if ronn-ng is mostly compatible with the old ronn for users.

Yes, ronn-ng is a drop-in replacement for users. It provides the same `ronn` command with the same options; just with bug fixes and some enhancements.

> As for build system (Makefile, etc), personally I know nothing about Ruby ecosystem but I guess a standard and universal buildsystem would certainly be better than a custom Makefile.

Ruby has a standard build system comprised of rake/gem/bundler. But that's mostly aimed at libraries, not applications: it doesn't support installing man pages, shell completion files, or the like. So I'm thinking of something like a Makefile to sit on top of rake/gem/bundler and do the additional steps for installing those bits.

**Comment by boutil** [comment]
Debian has recently switched to this fork to provide the ronn tool:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917318
It should be included in the next stable version, but currently it is affected by https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921637 (which is the same as #24 , I believe). Since it is causing build failure for other packages, it can become a blocker issue for its inclusion in the near future.

**Comment by apjanke** [comment]
Uh oh! Thanks for pointing this out. I'll prioritize this.

**Comment by boutil** [comment]
Deadline is tight though: for inclusion in the next stable release, a new version fixing this should be uploaded to the Debian archive....

**Comment by apjanke** [comment]
I don't think I made the March 1 deadline, but it looks like the Debian packagers pulled in the patches for this fix and applied it to their 0.8.0 copy, so it'll still be included in the next release (“buster”, I think).

**Comment by apjanke** [comment]
The fact that Debian has picked up Ronn-NG is good enough for me. Closing this as fixed.
