### ISSUE TITLE
Change markdown dependency?

### ISSUE THREAD

**Issue by deivid-rodriguez** [apjanke/ronn-ng#27]
I tried to install ronn-ng under jruby and got an error installing the `rdiscount` dependency. Not sure how hard would be to switch but https://github.com/gettalong/kramdown is one of the alternatives [recommended by jruby](https://github.com/jruby/jruby/wiki/C-Extension-Alternatives).

**Comment by deivid-rodriguez** [comment]
I started some work here: https://github.com/apjanke/ronn-ng/compare/master...deivid-rodriguez:migrate_to_kramdown.

Currently 1 failure in MRI and 9 failures on jruby: https://travis-ci.com/deivid-rodriguez/ronn-ng/builds/118124996.

**Comment by apjanke** [comment]
Yep, I'm good with switching to kramdown to support jruby. Work is ongoing in #28.
