### ISSUE TITLE
Cut 0.9.0 release

### ISSUE THREAD

**Issue by apjanke** [apjanke/ronn-ng#32]
The migration to kramdown justifies a new release, and a minor version bump. Cut an 0.9.0 once #28 is done.

**Comment by deivid-rodriguez** [comment]
Hei @apjanke, any new on the 0.9.0 release? Thanks :purple_heart:.

**Comment by apjanke** [comment]
I think we're good to go! Give me a couple hours and I'll roll this out.

**Comment by apjanke** [comment]
Version 0.9.0 is go.

![shipit-squirrel](https://user-images.githubusercontent.com/2618447/71315331-69c48500-2428-11ea-9a9e-1cda77cef5aa.jpg)

Please find the new release on RubyGems or here on GitHub.

**Comment by deivid-rodriguez** [comment]
Thanks!
