### ISSUE TITLE
incompatible encoding regexp match (Windows-31J regexp with UTF-8 string) 

### ISSUE THREAD

**Issue by Natim** [apjanke/ronn-ng#43]
This error occurs if the markdown file contains a unicode characters.
Refs amsardesai/middleman-protect-emails#2

version: ronn-ng 0.8.0

**Comment by apjanke** [comment]
Thanks for the report! I'll get on this.

Any chance you could attach a zip file of the particular markdown file that's causing `ronn` to fail here?

**Comment by Natim** [comment]
Fixed with ronn-ng 0.9.0 installed via gem.
I had the 0.8.0 version because it is the version provided with ubuntu 18.04 :confused:

**Comment by apjanke** [comment]
Good to hear it's fixed.

No worries about the noise! It's nice to know we've got users out there.
