### ISSUE TITLE
The single quote char (ASCII 39) is rendered as UTF apostrophe in roff

### ISSUE THREAD

**Issue by rd235** [apjanke/ronn-ng#55]
Thank you for the very useful tool.

Unfortunately I have found an issue: ronn translates single quote chars (this ') into apostrophe (this ´).

This causes a number of drawbacks:
* code blocks cannot be copy-paste into source code files
* debian lintian complaints:
"acute-accent-in-manual-page: This manual page uses the `\'` groff sequence. Usually, the intent to generate an apostrophe, but that sequence actually renders as a an acute accent."

The following file is an example of erroneously rendered man page.
[quote_error.7.ronn.txt](https://github.com/apjanke/ronn-ng/files/4945968/quote_error.7.ronn.txt)

IMHO the single quote should be a control char only when it is at the beginning of a line, so it shouldn't be escaped.
Here the following patch seems to generate the right roff translation of the man pages.
```
diff --git a/lib/ronn/roff.rb b/lib/ronn/roff.rb
index 3af434e..ac65042 100644
--- a/lib/ronn/roff.rb
+++ b/lib/ronn/roff.rb
@@ -339,7 +339,7 @@ module Ronn
       text.gsub!(/&#(\d+);/) { $1.to_i.chr }                # dec entities
       text.gsub!('\\', '\e')                                # backslash
       text.gsub!('...', '\|.\|.\|.')                        # ellipses
-      text.gsub!(/['.-]/) { |m| "\\#{m}" }                  # control chars
+      text.gsub!(/[.-]/) { |m| "\\#{m}" }                   # control chars
       ent.each do |key, val|
         text.gsub!(key, val)
       end
```

**Comment by apjanke** [comment]
Thanks! And you're welcome!

I agree with your analysis here.

The patch turns out to be more than a one-liner, because we still need to handle the edge case of "'" that are at the beginning of a line, by either padding or escaping them. Here's a PR: https://github.com/apjanke/ronn-ng/pull/58. This is tentatively scheduled to go out in Ronn-NG 0.10.0.
