### ISSUE TITLE
more -i is not portable

### ISSUE THREAD

**Issue by paravoid** [apjanke/ronn-ng#71]
ronn has:
```ruby
pager = ENV['MANPAGER'] || ENV['PAGER'] || 'more -is'
```

However, `more -i` does not work on my Debian buster system:
```shell
$ echo | more -is
more: unknown option -is
Try 'more --help' for more information.
```

And therefore, `ronn -m` fails out of the box.

**Comment by apjanke** [comment]
This was introduced in https://github.com/apjanke/ronn-ng/commit/f528c259185ad65009724c760ec2ba0cb0d847a1. Looks like I did not do my portability research: on macOS, `more` is an alias for `less`. `-i` is a `less` option, not a `more` option. I'll remove it.

Thanks for all the bug reports, by the way!

**Comment by apjanke** [comment]
Fixed in https://github.com/apjanke/ronn-ng/commit/33b8f549cf40e8585606aa102e1401ce157a572a.
