### ISSUE TITLE
4th-level headers (h4) are not displayed

### ISSUE THREAD

**Issue by paravoid** [apjanke/ronn-ng#72]
On a real-world manpage with a 4th-level header (`####`), ronn emits:
````
warn: unrecognized block tag: ["h4"]
````
…and fails to output the line altogether.

pandoc translates this to `.SS`, which is at the same level as the 3rd-level header, but is at least displayed.

**Comment by apjanke** [comment]
That sounds like a good behavior. We can change Ronn to do so.

**Comment by apjanke** [comment]
What do you think of this?

https://github.com/apjanke/ronn-ng/commit/e10a69c18782bcb1e6918ace284e712b3f96be2b

It translates 4th-through-6th-level headers to `.SS`, which will all look like 3rd-level headers, but they won't be dropped any more.

**Comment by paravoid** [comment]
Makes sense to me!

**Comment by apjanke** [comment]
Seems to be working since we made this change. Closing this ticket as fixed.
