### ISSUE TITLE
My Ruby env is busted; bundle install permission errors

### ISSUE THREAD

**Issue by apjanke** [apjanke/ronn-ng#92]
So, I tried to rebuild the man pages and a distro, and that didn't work. I want to build them using the local ronn. Broke due to bundler-managed gem dependency errors. Tried to do a `bundle install` in my local clone of the ronn-ng repo on my Mac running macOS 10.14, and got these errors.

In bash:

```
[ronn-ng] $ which bundle
/usr/local/lib/ruby/gems/2.6.0/bin/bundle
[ronn-ng] $ pwd
/Users/janke/repos/ronn-ng
[ronn-ng] $ date
Mon Jan  9 00:39:40 EST 2023
[ronn-ng] $ bundle install
bash: /usr/local/lib/ruby/gems/2.6.0/bin/bundle: cannot execute: required file not found
[ronn-ng] $
```

In zsh:

```
 ✘   bundle install
zsh: /usr/local/lib/ruby/gems/2.6.0/bin/bundle: bad interpreter: /usr/local/opt/ruby/bin/ruby: no such file or directory
Bundler 2.4.1 is running, but your lockfile was generated with 2.1.4. Installing Bundler 2.1.4 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.1.4
Installing bundler 2.1.4
There was an error installing the locked bundler version (2.1.4), rerun with the `--verbose` flag for more details. Going on using bundler 2.4.1.
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Resolving dependencies...
Could not find gem 'nokogiri (= 1.13.10)' with platform 'ruby' in rubygems repository https://rubygems.org/ or installed locally.

The source contains the following gems matching 'nokogiri (= 1.13.10)':
  * nokogiri-1.13.10-aarch64-linux
  * nokogiri-1.13.10-arm64-darwin
  * nokogiri-1.13.10-java
  * nokogiri-1.13.10
  * nokogiri-1.13.10-x64-mingw-ucrt
  * nokogiri-1.13.10-x64-mingw32
  * nokogiri-1.13.10-x86-linux
  * nokogiri-1.13.10-x86-mingw32
  * nokogiri-1.13.10-x86_64-darwin
  * nokogiri-1.13.10-x86_64-linux
📢   WIP/https-ify  janke@  ~/r/ronn-ng 
 ✘  
```

A couple days ago, I got a different error, with `bundle install` attempting to do the installs, and getting a bunch of permission errors when trying to write to some directory under the MacPorts-managed Ruby install under `/opt`.

**Comment by deivid-rodriguez** [comment]
You can upgrade Bundler using `bundle update --bundler` and commit the resulting `Gemfile.lock` file. That should at least get rid of the nokogiri not found errors.

**Comment by apjanke** [comment]
Oh, shoot! What do you think I should do here? Use MacPorts to set Ruby 3.1 as my main Ruby on this box? Or use RVM? Or...?

**Comment by deivid-rodriguez** [comment]
I recommend using a ruby version manager (I prefer asdf, or Rbenv, over RVM, but that's just my preference), and stick to Ruby 3.1 for now.

**Comment by apjanke** [comment]
Thanks @deivid-rodriguez. I'm going to try out these Ruby version managers while preparing for the 0.10.2 release.

In the mean time, everything is working well enough for me to do the 0.10.1 release: with the `$GEM_HOME` fix and rebuilding `Gemfile.lock` in the ronn-ng repo, everything including `liquid` seems to be working now, including under Ruby 3.2.0 (which I'm running on my local Mac via MacPorts).
