### ISSUE TITLE
bad link for ronn-format(7)

### ISSUE THREAD

**Issue by marczz** [apjanke/ronn-ng#99]
The link given for `ronn-format(7)` is dead. You should either link to the man page from Ryan Tomaykio at
[ronn-format(7)](http://rtomayko.github.io/ronn/ronn-format.7.html) or a widely available manpage like [ronn-format(7)](https://manpages.debian.org/unstable/ruby-ronn/ronn-format.7.en.html) or host the html output of  `ronn-format`.

**Comment by apjanke** [comment]
Thanks! I plan on handling this by hosting the HTML of all the ronn-ng man pages on a GitHub Pages site here. Coming soon...

**Comment by apjanke** [comment]
Fixed in https://github.com/apjanke/ronn-ng/commit/afaf6b66888b7d7083a94f9b14bb58b04b6533dc, now merged to `main`. Shipping in version 0.10.1, ETA within a week.
